name: tabix-utils
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::htslib
  - bioconda::vcftools
  - bioconda::bedtools
  - bioconda::bcftools
  - bioconda::tabix
  - conda-forge::gawk
  - conda-forge::gzip
